### ISSUE TITLE
Multiple calls crash R/Rstudio

### ISSUE THREAD

**Issue by SimonDedman** [rasmusab/beepr#26]
Hi Rasmus, thanks for the function, I use it in almost everything. However I've just realised it may have been the cause of all my crashed R sessions - please see this bug which RStudio team just closed cos it's probably not specific to them i.e. is an R core issue:

https://github.com/rstudio/rstudio/issues/3549#issuecomment-424953355

Thanks!

**Comment by rasmusab** [comment]
Hi @SimonDedman ,

One more thing, I've now push a (possible) fix. But since I'm on Linux and can't replicate the problem, it would be great if you could give it a try!

First, install the fix from github:

```
library(devtools)
install_github("rasmusab/beepr@develop")
```

Then try running the code that resulted in a crash before, and let me know if you still get a crash! :)

/R

**Comment by SimonDedman** [comment]
Hi Rasmus, sorry I never got back to you about this, must have slipped through my inbox unseen. I am/was Linux also. I suspect your fix worked, thanks for looking into this!
